// import localFont from "next/font/local";
import "./style.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
    weight: ['400', '700'],
    subsets: ['latin']
})

// const geistSans = localFont({
//     src: "../../fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "../../fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        {children}
        </body>
        </html>
    );
}
